dist: xenial
sudo: false
language: python
# command to install dependencies
install: "make"
cache: pip
jobs:
  include:
    - stage: test
      script:
        - make test-readme
        - make ci
      python: '2.7'
    - stage: test
      script:
        - make test-readme
        - make ci
      python: '3.4'
    - stage: test
      script:
        - make test-readme
        - make ci
      python: '3.5'
    - stage: test
      script:
        - make test-readme
        - make ci
      python: '3.6'
    - stage: test
      script:
        - make test-readme
        - make ci
      python: '3.7'
    - stage: coverage
      python: '3.7'
      script: codecov
