sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install tox
  - tox -e $TRAVIS_PYTHON_VERSION --notest

script: tox -e $TRAVIS_PYTHON_VERSION
# after_success: coveralls $COVERALLS_OPTION
