name: Lint code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
